---
- name: Configure journald to persist storage
  ansible.builtin.lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^#Storage='
    state: present
    backrefs: true
    line: 'Storage=persistent'
